---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/examples
  label: Examples
  create: all
  match: "**/*"
- type: directory
  path: content/schema
  label: Schema
  create: all
  match: "**/*"
- type: directory
  path: content/shortcodes
  label: Shortcodes
  create: all
  match: "**/*"
- type: directory
  path: content/config
  label: Config
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.49.2
